FROM ubuntu:14.04
MAINTAINER Open State Foundation <developers@openstate.eu>

# Use bash as default shell
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Add multiverse to sources
RUN echo 'deb http://archive.ubuntu.com/ubuntu/ trusty multiverse' >> etc/apt/sources.list

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

#Set Timezone
RUN echo "Europe/Amsterdam" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update \
    && apt-get install -y \
        python-dev \
        python-setuptools \
        python-software-properties \
        openjdk-7-jre-headless \
        wget \
        curl \
        poppler-utils \
        software-properties-common \
        autoconf \
        automake \
        libtool \
        gettext \
        git \
        dnsutils \
        inotify-tools \
        vim

RUN add-apt-repository ppa:mc3man/trusty-media \
    && apt-get update \
    && apt-get dist-upgrade -y

RUN apt-get update \
    && apt-get install -y \
        make \
        libxml2-dev \
        libxslt1-dev \
        libssl-dev \
        libffi-dev \
        libtiff4-dev \
        libjpeg8-dev \
        liblcms2-dev \
        python-virtualenv \
        supervisor

RUN pip install --upgrade pip

WORKDIR /opt/pfl
# Create a virtualenv project
RUN echo 'ok'
RUN virtualenv -q /opt
RUN echo "source /opt/bin/activate; cd /opt/pfl;" >> /etc/profile

# Temporarily add all pfl API files on the host to the container
# as it contains files needed to finish the base installation
ADD . /opt/pfl

# Install Python requirements
COPY ocd_backend/requirements-ml.txt /opt/pfl/requirements.txt
RUN source /opt/bin/activate \
    && pip install --upgrade pip \
    && pip install --upgrade setuptools \
    && pip install pycparser==2.13 \
    && pip install Cython==0.21.2 \
    && pip install -r requirements.txt

RUN apt-get install supervisor

WORKDIR /opt/pfl/
CMD tail -f README.md
